version: "3"

services:
  frontend:
    build: ./client
    container_name: react-ui
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-networks

  backend:
    build: ./server
    container_name: node-api
    ports:
      - "5050:5050"
    volumes:
      - ./server:/usr/src/app
    restart: always
    depends_on:
      - database
    environment:
      - DATABASE_URI=mongodb://mongo-db:27017/
    networks:
      - mern-networks

  database:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-networks

networks:
  mern-networks:
    driver: bridge

volumes:
  mongo-data:
